INSERT INTO user (name, age, email, password)
VALUES ('Max', 12, 'Max@gmail.com',
        '$2a$10$TTNZP/stgyPVxlb6hlph1.kPMXxQh7QPJ4btHJ8BY7AwP5PMjhTBm'),
       ('Anna', 55, 'Anna@gmail.com',
        '$2a$10$irmDgO6vB.31Fm7h.t/Vy.22.IfCW/pXfCxUZY.R0stjlzcL6I702'),
       ('Alexis', 10, 'Alexis@gmail.com',
        '$2a$10$h3X25yT7uxdIcbPFPdxfk.CbpiAbm0/JvIkNxWItvvSp/QFo7eBda'),
       ('Alice', 80, 'Alice@gmail.com',
        '$2a$10$dWhEG5eXKueBQH7.RGJS6.giXj/uR59Nyz.wxGhOsgTT6ohHSibky'),
       ('Anselm', 21, 'Anselm@gmail.com',
        '$2a$10$a9qtdXCaxUTQtLjwoUwwb.PST9AmWLQhoKpy738UqQ1Y0q.eykHJO'),
       ('April', 40, 'April@gmail.com',
        '$2a$10$SZ3JQXA62qabzRBjzoYZHOYtUgyYiNruF0V57na9PDQ/5L/SfxQ4G'),
       ('Bruce', 31, 'Bruce@gmail.com',
        '$2a$10$0MICOIkcJr5KONbv44Xg0OwIZTqb2lUqxSraX6XZhSuu7HDuctP/q'),
       ('Clara', 8, 'Clara@gmail.com',
        '$2a$10$hXr9AYsAx1eJse3RhcpRLOhVkREAaPctLSkPt/05Q8Fk4OTTvnTBK'),
       ('Dora', 3, 'Dora@gmail.com',
        '$2a$10$sXMdv91mmdclCkm8bXoXV.XvMgSBRETwO4c4krUxU7WyjKDQMrMKK'),
       ('Dorothy', 19, 'Dorothy@gmail.com',
        '$2a$10$ZJ6ckRHdkeiSXQLR1kSPGun/ZOu6BF9xQEajmQAJDzUL1X2gagdxq');

INSERT INTO article (user_id, color, text)
VALUES (1, 'RED', 'Carrie'),
       (1, 'RED', 'Salems Lot'),
       (1, 'BLUE', 'The Shining'),
       (1, 'GREEN', 'Rage'),
       (2, 'BLUE', 'The Long Walk'),
       (3, 'RED', 'The Dead Zone'),
       (4, 'GREEN', 'Firestarter'),
       (5, 'BLUE', 'Roadwork'),
       (6, 'YELLOW', 'Cujo'),
       (6, 'YELLOW', 'The Running Man'),
       (6, 'BLACK', 'The Dark Tower: The Gunslinger'),
       (6, 'BLACK', 'Christine'),
       (7, 'BLACK', 'Pet Sematary'),
       (8, 'RED', 'Cycle of the Werewolf'),
       (8, 'VIOLET', 'The Talisman'),
       (8, 'VIOLET', 'The Eyes of the Dragon'),
       (8, 'RED', 'Thinner'),
       (8, 'BLACK', 'It'),
       (9, 'GREEN', 'Misery'),
       (10, 'VIOLET', 'The Stand'),
       (10, 'GREEN', 'The Dark Half'),
       (10, 'ORANGE', 'Needful Things'),
       (10, 'VIOLET', 'Insomnia'),
       (10, 'BLUE', 'The Stand');